/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Apollo(props) {
  const { nodes, materials } = useGLTF('/apollo.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[0.16, -0.07, -0.43]}>
        <mesh
          geometry={nodes['x3d-cm-exterior-filler'].geometry}
          material={materials['Default OBJ.002']}
          position={[0, -166.82, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={
            nodes['x3d-cm-exterior-shell-90k-uvs-150k-unwrapped'].geometry
          }
          material={materials['Default OBJ.001']}
          position={[0, -166.82, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <group position={[0, -166.82, 0]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={
              nodes['x3d-cm-exterior-top-160k-uvs-150k-unwrapped_1'].geometry
            }
            material={materials['Default OBJ']}
          />
          <mesh
            geometry={
              nodes['x3d-cm-exterior-top-160k-uvs-150k-unwrapped_2'].geometry
            }
            material={materials['Default OBJ']}
          />
          <mesh
            geometry={
              nodes['x3d-cm-exterior-top-160k-uvs-150k-unwrapped_3'].geometry
            }
            material={materials['Default OBJ']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/apollo.glb')
